version: '3.8'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    environment:
      - DAGSTER_HOME=/app/dagster_home
    volumes:
      - ./job_ads_pipeline.duckdb:/app/job_ads_pipeline.duckdb
    ports:
      - "3000:3000"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    volumes:
      - ./job_ads_pipeline.duckdb:/app/job_ads_pipeline.duckdb
    ports:
      - "8501:8501"
    depends_on:
      - pipeline
