
FROM python:3.11-slim


WORKDIR /app


COPY dashboard/ /app/dashboard/


RUN pip install streamlit duckdb pandas


EXPOSE 8501


CMD ["streamlit", "run", "dashboard/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
